- name: configuring nodejs
  become: yes
  hosts: catalogue
  tasks:
  - name: disabling nodejs
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enabling nodejs
    ansible.builtin.command: dnf module enable nodejs:20 -y
    register: command_output

  - name: installing nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present

  - name: create app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Add application User
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      system: true
      home: /app

  - name: Unarchive a file that needs to be downloaded
    ansible.builtin.unarchive:
      src: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip # downloand and unarchive
      dest: /app
      remote_src: yes

  - name: Update packages based on package.json to their latest version.
    community.general.npm:
      path: /app
      state: latest

  - name: Copying catalogue.service
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service

  - name: systemctl deamon reload
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: start and enable catalogue
    ansible.builtin.service:
      name: catalogue
      state: started
      enabled: yes

  - name: copy mongodb repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: install mongodb client
    ansible.builtin.dnf:
      name: mongodb-mongosh
      state: present

  - name: check products loaded or not
    ansible.builtin.command: mongosh --host mongodb.dsops84.space --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
    register: catalogue_output

  - name: print catalogue output
    ansible.builtin.debug:
      msg: "{{ catalogue_output }}"

  - name: load products
    ansible.builtin.shell: mongosh --host mongodb.dsops84.space < /app/db/master-data.js
    when: catalogue_output.stdout | int < 0