- name: configuring nodejs
  become: yes
  hosts: catalogue
  tasks:
  - name: disabling nodejs
    ansible.builtin.command: dnf module disable nodejs -y

  - name: disabling nodejs
    ansible.builtin.command: dnf module enable nodejs:20 -y
    register: command_output

  - name: installing nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present

  - name: Add application User
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      system: true
      home: /app

  - name: create app directory
    ansible.builtin.file:
      path: /app
      state: directory
      